stages:
  data_ingestion:
    cmd: python src/cnn_classifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/cnn_classifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Chicken-fecal-images


  prepare_base_model:
    cmd: python src/cnn_classifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/cnn_classifier/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - CLASSES
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model

  training:
    cmd: python src/cnn_classifier/pipeline/stage_03_training.py
    deps:
      - src/cnn_classifier/pipeline/stage_03_training.py
      - config/config.yaml
      - artifacts/data_ingestion/Chicken-fecal-images
      - artifacts/prepare_base_model
    params:
      - EPOCHS
      - BATCH_SIZE
      - LEARNING_RATE
    outs:
      - artifacts/training/trained_model.pt

  evaluation:
    cmd: python src/cnn_classifier/pipeline/stage_04_evaluation.py
    deps:
      - src/cnn_classifier/pipeline/stage_04_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/Chicken-fecal-images
      - artifacts/training/trained_model.pt
    params:
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false
